apiVersion: v1
kind: Service
metadata:
  name: srv-gym-investire-iscritto-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gym-investire-iscritto-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
